#!/usr/bin/env python3
"""Copy this integration into a sibling built-in source tree.

The Groovy files here are the source of truth. Run this script after changes;
use --check to detect copies that need refreshing without writing anything.
"""

import argparse
import re
import sys
from pathlib import Path


SOURCE_DIR = Path(__file__).resolve().parent
DEFAULT_TARGET = SOURCE_DIR.parent.parent / "driversAndApps_2.5.2"
NAMESPACE = "hubitat"
DESTINATION_FOLDER = "jdthomas24"
DESTINATION_PREFIX = "jdthomas24_"
APP = "ParentApp.groovy"
DRIVERS = (
    "CameraDriver.groovy",
    "DoorbellDriver.groovy",
    "ReolinkDeviceBridge.groovy",
    "StandaloneDevices.groovy",
)
HEADER = (
    "// GENERATED by Reolink Integration/jdthomas24_sync_builtin.py. "
    "Edit the source repository, then rerun the script.\n"
)
NAMESPACE_REFERENCE = re.compile(
    r'(?P<prefix>\bnamespace\s*:\s*|\baddChildDevice\s*\(\s*)"jdthomas24"'
)


def generated_source(filename: str) -> str:
    """Return the built-in copy of a source file.

    Args:
        filename: Groovy filename in this integration directory.

    Returns:
        Generated Groovy source with matching namespace and child references.
    """
    source = (SOURCE_DIR / filename).read_text(encoding="utf-8")
    transformed, count = NAMESPACE_REFERENCE.subn(
        lambda match: f'{match.group("prefix")}"{NAMESPACE}"', source
    )
    if count == 0 or f'namespace: "{NAMESPACE}"' not in transformed:
        raise ValueError(f"Expected a namespace declaration in {filename}")
    return HEADER + transformed


def destinations(target: Path) -> dict[str, Path]:
    """Map each source filename to its destination in the built-in tree.

    Args:
        target: Root of the driversAndApps checkout.

    Returns:
        Destination path for the app and each driver.
    """
    result = {
        APP: target / "apps" / "src" / DESTINATION_FOLDER /
        f"{DESTINATION_PREFIX}{APP}"
    }
    result.update(
        {name: target / "devicetypes" / "src" / DESTINATION_FOLDER /
         f"{DESTINATION_PREFIX}{name}"
         for name in DRIVERS}
    )
    return result


def main() -> int:
    """Check or update the generated copies and return a process exit code.

    Returns:
        Zero when copies match or were updated; one on drift or unsafe output.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=Path, default=DEFAULT_TARGET,
                        help="driversAndApps checkout (default: sibling driversAndApps_2.5.2)")
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args()
    target = args.target.resolve()
    if not (target / "apps" / "src").is_dir() or not (target / "devicetypes" / "src").is_dir():
        parser.error(f"Not a driversAndApps source tree: {target}")

    pending = []
    for filename, output in destinations(target).items():
        content = generated_source(filename)
        existing = output.read_text(encoding="utf-8") if output.exists() else None
        if existing == content:
            print(f"up to date: {output}")
            continue
        # Refuse to replace files that were not created by this script.
        if existing is not None and not existing.startswith(HEADER):
            print(f"refusing to overwrite unmanaged file: {output}", file=sys.stderr)
            return 1
        pending.append((output, content))

    if args.check:
        for output, _ in pending:
            print(f"out of date: {output}")
        return 1 if pending else 0

    for output, content in pending:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
        print(f"updated: {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
